//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id_product { get; set; }
        public string fldname { get; set; }
        public decimal fldprice { get; set; }
        public System.DateTime flddateOn { get; set; }
        public bool fldactive { get; set; }
        public int id_fktypeProduct { get; set; }
    
        public virtual c_typeProduct c_typeProduct { get; set; }
    }
}
